#!/usr/bin/env python3
"""Documentation generator (Phase 11).

Auto-builds browsable reference docs from the data already in the repo:
module maps, fault-code tables, MS41 RAM parameters, and each Python
module's docstrings/API. Pure stdlib, offline, writes to docs/.

Run:  python3 gen_docs.py   ->  docs/{MODULES,FAULT_CODES,PARAMETERS,API}.md
"""
import ast
import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DOCS = os.path.join(HERE, "docs")


def _load(name):
    try:
        with open(os.path.join(HERE, name), encoding="utf-8") as f:
            return json.load(f)
    except (OSError, ValueError):
        return {}


def gen_modules():
    """Module address maps for both cars, from the protocol modules."""
    import importlib.util
    lines = ["# Module Reference\n",
             "Auto-generated by gen_docs.py. Do not edit by hand.\n"]

    spec = importlib.util.spec_from_file_location(
        "ds2_diag", os.path.join(HERE, "ds2_diag.py"))
    ds2 = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(ds2)
        lines.append("\n## E39 (DS2) modules\n")
        lines.append("| Addr | Module | Fault texts |")
        lines.append("|------|--------|-------------|")
        for addr, name in sorted(ds2.E39_MODULES.items()):
            has = "yes" if addr in getattr(ds2, "DTC_TABLES", {}) else "-"
            lines.append(f"| 0x{addr:02X} | {name} | {has} |")
    except Exception as e:
        lines.append(f"\n_(could not load ds2_diag: {e})_")

    spec = importlib.util.spec_from_file_location(
        "power_diag", os.path.join(HERE, "power_diag.py"))
    pd = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(pd)
        lines.append("\n## E87 (KWP2000) modules\n")
        lines.append("| Addr | Module |")
        lines.append("|------|--------|")
        for addr, name in sorted(pd.MODULES.items()):
            lines.append(f"| 0x{addr:02X} | {name} |")
    except Exception as e:
        lines.append(f"\n_(could not load power_diag: {e})_")
    return "\n".join(lines) + "\n"


def gen_fault_codes():
    lines = ["# Fault Code Reference\n",
             "Auto-generated. Sources: OpenMS41 (DME), BMW SGBD docs "
             "(body modules), researched E87 codes.\n"]
    body = _load("e39_body_dtc_en.json")
    names = {"0x44": "EWS (immobiliser)", "0x56": "ABS/DSC",
             "0x80": "Instrument cluster (IKE)", "0x5B": "Climate (IHKA)",
             "0xD0": "Light module (LCM)", "0x60": "Park distance (PDC)",
             "0xE8": "Remote receiver (FBZV)"}
    for addr, entry in body.items():
        if not addr.startswith("0x"):
            continue
        lines.append(f"\n## {addr} — {names.get(addr, '')}\n")
        ort = entry.get("ort", {})
        if ort:
            lines.append("| Code | Location |")
            lines.append("|------|----------|")
            for code, text in sorted(ort.items(), key=lambda kv: int(kv[0])):
                lines.append(f"| 0x{int(code):02X} | {text} |")
        art = entry.get("art", {})
        if art:
            lines.append("\n**Fault types:** " +
                         ", ".join(f"0x{int(k):02X}={v}"
                                   for k, v in sorted(art.items(),
                                                      key=lambda kv: int(kv[0]))))
    dme = _load("ms41_dtc.json")
    if dme:
        lines.append(f"\n## 0x12 — DME (MS41), {len(dme)} codes\n")
        lines.append("See `ms41_dtc.json` for the full table "
                     "(decimal code -> text).")
    e87 = _load("e87_dtc.json")
    if e87:
        lines.append("\n## E87 (KWP2000) researched codes\n")
        lines.append("| Code | Meaning |")
        lines.append("|------|---------|")
        for code, text in e87.items():
            lines.append(f"| {code} | {text} |")
    return "\n".join(lines) + "\n"


def gen_parameters():
    params = _load("ms41_ram_params.json")
    lines = ["# MS41 Live Parameters (RAM)\n",
             "Auto-generated from ms41_ram_params.json "
             "(RomRaider logger definition, ECU 1429861).\n",
             "| ID | Name | Address | Type | Units | Formula |",
             "|----|------|---------|------|-------|---------|"]
    for p in params:
        lines.append(f"| {p.get('id')} | {p.get('name')} | "
                     f"{p.get('addr')} | {p.get('storagetype')} | "
                     f"{p.get('units')} | `{p.get('expr')}` |")
    return "\n".join(lines) + "\n"


def gen_api():
    """Extract module + public-function docstrings from the .py files."""
    lines = ["# Code / API Reference\n",
             "Auto-generated from module and function docstrings.\n"]
    for path in sorted(glob.glob(os.path.join(HERE, "*.py"))):
        name = os.path.basename(path)
        if name.startswith("test_") or name == "gen_docs.py":
            continue
        try:
            tree = ast.parse(open(path, encoding="utf-8").read())
        except (OSError, SyntaxError):
            continue
        mod_doc = ast.get_docstring(tree)
        lines.append(f"\n## `{name}`\n")
        if mod_doc:
            lines.append(mod_doc.strip().split("\n\n")[0] + "\n")
        funcs = []
        for node in tree.body:
            if isinstance(node, (ast.FunctionDef, ast.ClassDef)):
                d = ast.get_docstring(node)
                if d and not node.name.startswith("_"):
                    kind = "class" if isinstance(node, ast.ClassDef) else "def"
                    funcs.append(f"- **{kind} `{node.name}`** — "
                                 f"{d.strip().splitlines()[0]}")
        lines.extend(funcs)
    return "\n".join(lines) + "\n"


def gen_operations():
    """Operation database with evidence grades (Protocol Explorer)."""
    lines = ["# Operation Database\n",
             "Auto-generated from operations.json. Each operation carries a "
             "graded evidence level, not a binary status.\n",
             "**Grades:** verified (implemented + tested) · "
             "implemented-safe · observed (seen in a trace) · "
             "documented (in a BMW SGBD job, not yet on the wire).\n"]
    try:
        import operations as ops_mod
        db = ops_mod.OperationDB.load()
    except (OSError, ValueError):
        return "\n".join(lines) + "\n_(operations.json not built)_\n"
    s = db.summary()
    lines.append(f"**Totals:** {s['total']} operations across "
                 f"{len(db.ecus())} ECUs; {s['by_grade']}; "
                 f"{s['usable_on_car']} usable on car.\n")
    for ecu in db.ecus():
        ops = db.all(ecu=ecu)
        lines.append(f"\n## {ecu} ({len(ops)} operations)\n")
        lines.append("| Job | Kind | Grade | Car-usable | Description |")
        lines.append("|-----|------|-------|-----------|-------------|")
        for o in sorted(ops, key=lambda x: (x["kind"], x["name"])):
            lines.append(
                f"| {o.get('sgbd_job') or o['name']} | {o['kind']} | "
                f"{ops_mod.evidence_grade(o)} | "
                f"{'yes' if ops_mod.usable_on_car(o) else 'gated'} | "
                f"{(o.get('description') or '')[:60]} |")
    return "\n".join(lines) + "\n"


def generate_all():
    os.makedirs(DOCS, exist_ok=True)
    outputs = {
        "MODULES.md": gen_modules(),
        "FAULT_CODES.md": gen_fault_codes(),
        "PARAMETERS.md": gen_parameters(),
        "OPERATIONS.md": gen_operations(),
        "API.md": gen_api(),
    }
    written = []
    for name, content in outputs.items():
        p = os.path.join(DOCS, name)
        with open(p, "w", encoding="utf-8") as f:
            f.write(content)
        written.append((name, content.count("\n")))
    return written


if __name__ == "__main__":
    for name, lines in generate_all():
        print(f"wrote docs/{name} ({lines} lines)")
